version: "3"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db_sql:/var/lib/pgsql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: L4RPEverywhere!
      POSTGRES_DB: NexusLARP
      
      

  dockercomposeproductapi:
    image: nexusdatalayerapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6001:80"
    depends_on:
      - "db"
    networks:
      - product-network
      
  volumes:
    db_sql:      
      


networks:
    product-network:
        driver: bridge