  version: "3"

        services:
          postgres_db:
            image: postgres:11
            container_

name: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: L4RPEverywhere!
          POSTGRES_DB: NexusLARP
        restart: always
        volumes:
          - postgres_data:/var/lib/postgresql/data
        ports:
          - '5433:5432'
          
      dockercomposeproductapi:
        image: nexusdatalayerapi
        build:
        context: .
        dockerfile: Dockerfile
        ports:
          - "6001:80"
        depends_on:
          - postgres_db