version: "3"
services:
  dockercomposeproductapi:
    image: nexusdatalayerapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6001:80"
    networks:
      - product-network
    network_mode: "host"

networks:
    product-network: null