on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch: {}
  schedule:
    - cron: "0 3 * * *" # daily at 03:00 UTC


name: Secrets detection (Gitleaks)

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    name: Run Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: detect --source . --redact --verbose --exit-code 1 --config .gitleaks.toml

      # Optionally upload SARIF to code scanning (if supported by this action output)
      # - name: Upload SARIF results
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: gitleaks.sarif
