name: Trivy Security Scan

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "30 2 * * *" # daily at 02:30 UTC

permissions:
  contents: read
  security-events: write

jobs:
  trivy-fs-scan:
    name: Trivy FS Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner (filesystem)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          scanners: 'vuln,secret,misconfig'
          # cache to speed up scans
          cache-dir: ~/.cache/trivy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}